version: '3.8'

services:
    wordpress:
        image: wordpress:latest
        container_name: engaged-philosophy-wp
        ports:
            - '8080:80'
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        volumes:
            - ./:/var/www/html/wp-content/themes/engaged-philosophy
            - wordpress_data:/var/www/html
        depends_on:
            - db
        restart: unless-stopped

    db:
        image: mysql:8.0
        container_name: engaged-philosophy-db
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - db_data:/var/lib/mysql
        restart: unless-stopped

volumes:
    wordpress_data:
    db_data:
