name: Integration Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    needs: [frontend-check, php-check]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, curl
        coverage: none

    - name: Install all dependencies
      run: |
        npm ci
        composer install --prefer-dist --no-progress --no-interaction

    - name: Full build integration test
      run: |
        echo "🔧 Running full build integration test..."
        npm run build
        
        # Verify all expected files are generated
        test -f build/style.css || (echo "❌ Missing build/style.css" && exit 1)
        test -f build/index.js || (echo "❌ Missing build/index.js" && exit 1)
        test -f style.css || (echo "❌ Missing theme style.css" && exit 1)
        
        echo "✅ Full integration build successful"


  frontend-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Frontend workflow status
      run: echo "✅ Checking frontend workflow completion"

  php-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: PHP workflow status  
      run: echo "✅ Checking PHP workflow completion"